GET http://localhost:3000/users

###
GET http://localhost:3000/posts 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkRhdmlkIiwicGFzc3dvcmQiOiIkMmIkMTAkN2NEZ3hJVVpNeHBwY2RYdlBoUjlkLmtGSWpDb0E1TkY4OFJNa1VuTGtlV0pFYXZUZVFTMkMiLCJpYXQiOjE2NjU0NDYxNzUsImV4cCI6MTY2NTQ0NjIwMH0.qje7ugNQSUYT4oUM4Yy4NdwNbkjDYAsj5MNJl1fvG4g

###

POST http://localhost:3000/users
Content-Type: application/json

{
  "username": "David",
  "password": "password"
}

###

POST http://localhost:3000/token
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkRhdmlkIiwicGFzc3dvcmQiOiIkMmIkMTAkbU82OTV2NzJlUVZMZFFRMTB4UTAxdWM5N3BrYy45LjVtNnJTVzJ4TWE4QngySzBKZUgydXEiLCJpYXQiOjE2NjU0NDYzNDh9.io_l__U6xz9Z2smQ_6AxuH0nF4RKOAtd9rSep705pZY"
}

###

POST http://localhost:3000/users/login
Content-Type: application/json

{
  "username": "David",
  "password": "password"
}

###

DELETE http://localhost:3000/users/logout
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkRhdmlkIiwicGFzc3dvcmQiOiIkMmIkMTAkbU82OTV2NzJlUVZMZFFRMTB4UTAxdWM5N3BrYy45LjVtNnJTVzJ4TWE4QngySzBKZUgydXEiLCJpYXQiOjE2NjU0NDYzNDh9.io_l__U6xz9Z2smQ_6AxuH0nF4RKOAtd9rSep705pZY"
}